# Generated by Django 4.0.3 on 2022-05-19 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessName', models.CharField(max_length=100, null=True)),
                ('notes', models.CharField(default='no notes', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100, null=True)),
                ('employeeEmail', models.CharField(max_length=100, null=True)),
                ('employeePassword', models.CharField(max_length=100, null=True)),
                ('accountLevel', models.CharField(choices=[('admin', 'admin'), ('user', 'user'), ('employee', 'employee'), ('dimission', 'dimission')], default='employee', max_length=10)),
                ('employeeDepartment', models.CharField(choices=[('IT', 'Information Technology'), ('HR', 'Human Resources')], default='IT', max_length=10)),
                ('employeeNotes', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessName', models.CharField(max_length=100, null=True)),
                ('action', models.CharField(max_length=100, null=True)),
                ('actTo', models.CharField(max_length=100, null=True)),
                ('actBy', models.CharField(max_length=100, null=True)),
                ('actionDate', models.DateField(null=True)),
                ('recordTime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.access')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('types', models.ManyToManyField(to='accounts.type')),
            ],
        ),
        migrations.AddField(
            model_name='access',
            name='grantTo',
            field=models.ManyToManyField(through='accounts.link', to='accounts.employee'),
        ),
    ]
