# Generated by Django 4.0.3 on 2022-05-19 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='link',
            new_name='Grant',
        ),
    ]
