# Generated by Django 4.0.3 on 2022-05-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_link_grant'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='rights',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
